#ifndef CACHE_H_HEADER_GUIRD
#define CACHE_H_HEADER_GUIRD

#define MSGTLB00 "Null descriptor, this byte contains no information"
#define MSGTLB01 "Instruction TLB: 4 KByte pages, 4-way set associative, 32 entries"
#define MSGTLB02 "Instruction TLB: 4 MByte pages, fully associative, 2 entries"
#define MSGTLB03 "Data TLB: 4 KByte pages, 4-way set associative, 64 entries"
#define MSGTLB04 "Data TLB: 4 MByte pages, 4-way set associative, 8 entries"
#define MSGTLB05 "Data TLB1: 4 MByte pages, 4-way set associative, 32 entries"
#define MSGTLB06 "1st-level instruction cache: 8 KBytes, 4-way set associative, 32 byte line size"
#define MSGTLB07 ""
#define MSGTLB08 "1st-level instruction cache: 16 KBytes, 4-way set associative, 32 byte line size"
#define MSGTLB09 "1st-level instruction cache: 32KBytes, 4-way set associative, 64 byte line size"
#define MSGTLB0A "1st-level data cache: 8 KBytes, 2-way set associative, 32 byte line size"
#define MSGTLB0B "Instruction TLB: 4 MByte pages, 4-way set associative, 4 entries"
#define MSGTLB0C "1st-level data cache: 16 KBytes, 4-way set associative, 32 byte line size"
#define MSGTLB0D "1st-level data cache: 16 KBytes, 4-way set associative, 64 byte line size"
#define MSGTLB0E "1st-level data cache: 24 KBytes, 6-way set associative, 64 byte line size"
#define MSGTLB0F ""

#define MSGTLB10 ""
#define MSGTLB11 ""
#define MSGTLB12 ""
#define MSGTLB13 ""
#define MSGTLB14 ""
#define MSGTLB15 ""
#define MSGTLB16 ""
#define MSGTLB17 ""
#define MSGTLB18 ""
#define MSGTLB19 ""
#define MSGTLB1A ""
#define MSGTLB1B ""
#define MSGTLB1C ""
#define MSGTLB1D "2nd-level cache: 128 KBytes, 2-way set associative, 64 byte line size"
#define MSGTLB1E ""
#define MSGTLB1F ""

#define MSGTLB20 ""
#define MSGTLB21 "2nd-level cache: 256 KBytes, 8-way set associative, 64 byte line size"
#define MSGTLB22 "3rd-level cache: 512 KBytes, 4-way set associative, 64 byte line size, 2 lines per sector"
#define MSGTLB23 "3rd-level cache: 1 MBytes, 8-way set associative, 64 byte line size, 2 lines per sector"
#define MSGTLB24 "2nd-level cache: 1 MBytes, 16-way set associative, 64 byte line size"
#define MSGTLB25 "3rd-level cache: 2 MBytes, 8-way set associative, 64 byte line size, 2 lines per sector"
#define MSGTLB26 ""
#define MSGTLB27 ""
#define MSGTLB28 ""
#define MSGTLB29 "3rd-level cache: 4 MBytes, 8-way set associative, 64 byte line size, 2 lines per sector"
#define MSGTLB2A ""
#define MSGTLB2B ""
#define MSGTLB2C "1st-level data cache: 32 KBytes, 8-way set associative, 64 byte line size"
#define MSGTLB2D ""
#define MSGTLB2E ""
#define MSGTLB2F ""

#define MSGTLB30 "1st-level instruction cache: 32 KBytes, 8-way set associative, 64 byte line size"
#define MSGTLB31 ""
#define MSGTLB32 ""
#define MSGTLB33 ""
#define MSGTLB34 ""
#define MSGTLB35 ""
#define MSGTLB36 ""
#define MSGTLB37 ""
#define MSGTLB38 ""
#define MSGTLB39 ""
#define MSGTLB3A ""
#define MSGTLB3B ""
#define MSGTLB3C ""
#define MSGTLB3D ""
#define MSGTLB3E ""
#define MSGTLB3F ""

#define MSGTLB40 "No 2nd-level cache or, if processor contains a valid 2nd-level cache, no 3rd-level cache"
#define MSGTLB41 "2nd-level cache: 128 KBytes, 4-way set associative, 32 byte line size"
#define MSGTLB42 "2nd-level cache: 256 KBytes, 4-way set associative, 32 byte line size"
#define MSGTLB43 "2nd-level cache: 512 KBytes, 4-way set associative, 32 byte line size"
#define MSGTLB44 "2nd-level cache: 1 MByte, 4-way set associative, 32 byte line size"
#define MSGTLB45 "2nd-level cache: 2 MByte, 4-way set associative, 32 byte line size"
#define MSGTLB46 "3rd-level cache: 4 MByte, 4-way set associative, 64 byte line size"
#define MSGTLB47 "3rd-level cache: 8 MByte, 8-way set associative, 64 byte line size"
#define MSGTLB48 "2nd-level cache: 3MByte, 12-way set associative, 64 byte line size"
#define MSGTLB49 "3rd-level cache: 4MB, 16-way set associative, 64-byte line size (Intel Xeon processor MP, Family 0FH, Model 06H); 2nd-level cache: 4 MByte, 16-way set associative, 64 byte line size"
#define MSGTLB4A "3rd-level cache: 6MByte, 12-way set associative, 64 byte line size"
#define MSGTLB4B "3rd-level cache: 8MByte, 16-way set associative, 64 byte line size"
#define MSGTLB4C "3rd-level cache: 12MByte, 12-way set associative, 64 byte line size"
#define MSGTLB4D "3rd-level cache: 16MByte, 16-way set associative, 64 byte line size"
#define MSGTLB4E "2nd-level cache: 6MByte, 24-way set associative, 64 byte line size"
#define MSGTLB4F "Instruction TLB: 4 KByte pages, 32 entries"

#define MSGTLB50 "Instruction TLB: 4 KByte and 2-MByte or 4-MByte pages, 64 entries"
#define MSGTLB51 "Instruction TLB: 4 KByte and 2-MByte or 4-MByte pages, 128 entries"
#define MSGTLB52 "Instruction TLB: 4 KByte and 2-MByte or 4-MByte pages, 256 entries"
#define MSGTLB53 ""
#define MSGTLB54 ""
#define MSGTLB55 "Instruction TLB: 2-MByte or 4-MByte pages, fully associative, 7 entries"
#define MSGTLB56 "Data TLB0: 4 MByte pages, 4-way set associative, 16 entries"
#define MSGTLB57 "Data TLB0: 4 KByte pages, 4-way associative, 16 entries"
#define MSGTLB58 ""
#define MSGTLB59 "Data TLB0: 4 KByte pages, fully associative, 16 entries"
#define MSGTLB5A "Data TLB0: 2-MByte or 4 MByte pages, 4-way set associative, 32 entries"
#define MSGTLB5B "Data TLB: 4 KByte and 4 MByte pages, 64 entries"
#define MSGTLB5C "Data TLB: 4 KByte and 4 MByte pages,128 entries"
#define MSGTLB5D "Data TLB: 4 KByte and 4 MByte pages,256 entries"
#define MSGTLB5E ""
#define MSGTLB5F ""

#define MSGTLB60 "1st-level data cache: 16 KByte, 8-way set associative, 64 byte line size"
#define MSGTLB61 "Instruction TLB: 4 KByte pages, fully associative, 48 entries"
#define MSGTLB62 ""
#define MSGTLB63 "Data TLB: 1 GByte pages, 4-way set associative, 4 entries"
#define MSGTLB64 ""
#define MSGTLB65 ""
#define MSGTLB66 "1st-level data cache: 8 KByte, 4-way set associative, 64 byte line size"
#define MSGTLB67 "1st-level data cache: 16 KByte, 4-way set associative, 64 byte line size"
#define MSGTLB68 "1st-level data cache: 32 KByte, 4-way set associative, 64 byte line size"
#define MSGTLB69 ""
#define MSGTLB6A ""
#define MSGTLB6B ""
#define MSGTLB6C ""
#define MSGTLB6D ""
#define MSGTLB6E ""
#define MSGTLB6F ""

#define MSGTLB70 "Trace cache: 12 K-μop, 8-way set associative"
#define MSGTLB71 "Trace cache: 16 K-μop, 8-way set associative"
#define MSGTLB72 "Trace cache: 32 K-μop, 8-way set associative"
#define MSGTLB73 ""
#define MSGTLB74 ""
#define MSGTLB75 ""
#define MSGTLB76 "Instruction TLB: 2M/4M pages, fully associative, 8 entries"
#define MSGTLB77 ""
#define MSGTLB78 "2nd-level cache: 1 MByte, 4-way set associative, 64byte line size"
#define MSGTLB79 "2nd-level cache: 128 KByte, 8-way set associative, 64 byte line size, 2 lines per sector"
#define MSGTLB7A "2nd-level cache: 256 KByte, 8-way set associative, 64 byte line size, 2 lines per sector"
#define MSGTLB7B "2nd-level cache: 512 KByte, 8-way set associative, 64 byte line size, 2 lines per sector"
#define MSGTLB7C "2nd-level cache: 1 MByte, 8-way set associative, 64 byte line size, 2 lines per sector"
#define MSGTLB7D "2nd-level cache: 2 MByte, 8-way set associative, 64byte line size"
#define MSGTLB7E ""
#define MSGTLB7F "2nd-level cache: 512 KByte, 2-way set associative, 64-byte line size"

#define MSGTLB80 "2nd-level cache: 512 KByte, 8-way set associative, 64-byte line size"
#define MSGTLB81 ""
#define MSGTLB82 "2nd-level cache: 256 KByte, 8-way set associative, 32 byte line size"
#define MSGTLB83 "2nd-level cache: 512 KByte, 8-way set associative, 32 byte line size"
#define MSGTLB84 "2nd-level cache: 1 MByte, 8-way set associative, 32 byte line size"
#define MSGTLB85 "2nd-level cache: 2 MByte, 8-way set associative, 32 byte line size"
#define MSGTLB86 "2nd-level cache: 512 KByte, 4-way set associative, 64 byte line size"
#define MSGTLB87 "2nd-level cache: 1 MByte, 8-way set associative, 64 byte line size"
#define MSGTLB88 ""
#define MSGTLB89 ""
#define MSGTLB8A ""
#define MSGTLB8B ""
#define MSGTLB8C ""
#define MSGTLB8D ""
#define MSGTLB8E ""
#define MSGTLB8F ""

#define MSGTLB90 ""
#define MSGTLB91 ""
#define MSGTLB92 ""
#define MSGTLB93 ""
#define MSGTLB94 ""
#define MSGTLB95 ""
#define MSGTLB96 ""
#define MSGTLB97 ""
#define MSGTLB98 ""
#define MSGTLB99 ""
#define MSGTLB9A ""
#define MSGTLB9B ""
#define MSGTLB9C ""
#define MSGTLB9D ""
#define MSGTLB9E ""
#define MSGTLB9F ""

#define MSGTLBA0 "DTLB: 4k pages, fully associative, 32 entries"
#define MSGTLBA1 ""
#define MSGTLBA2 ""
#define MSGTLBA3 ""
#define MSGTLBA4 ""
#define MSGTLBA5 ""
#define MSGTLBA6 ""
#define MSGTLBA7 ""
#define MSGTLBA8 ""
#define MSGTLBA9 ""
#define MSGTLBAA ""
#define MSGTLBAB ""
#define MSGTLBAC ""
#define MSGTLBAD ""
#define MSGTLBAE ""
#define MSGTLBAF ""

#define MSGTLBB0 "Instruction TLB: 4 KByte pages, 4-way set associative, 128 entries"
#define MSGTLBB1 "Instruction TLB: 2M pages, 4-way, 8 entries or 4M pages, 4-way, 4 entries"
#define MSGTLBB2 "Instruction TLB: 4KByte pages, 4-way set associative, 64 entries"
#define MSGTLBB3 "Data TLB: 4 KByte pages, 4-way set associative, 128 entries"
#define MSGTLBB4 "Data TLB1: 4 KByte pages, 4-way associative, 256 entries"
#define MSGTLBB5 "Instruction TLB: 4KByte pages, 8-way set associative, 64 entries"
#define MSGTLBB6 "Instruction TLB: 4KByte pages, 8-way set associative, 128 entries"
#define MSGTLBB7 ""
#define MSGTLBB8 ""
#define MSGTLBB9 ""
#define MSGTLBBA "Data TLB1: 4 KByte pages, 4-way associative, 64 entries"
#define MSGTLBBB ""
#define MSGTLBBC ""
#define MSGTLBBD ""
#define MSGTLBBE ""
#define MSGTLBBF ""

#define MSGTLBC0 "Data TLB: 4 KByte and 4 MByte pages, 4-way associative, 8 entries"
#define MSGTLBC1 "Shared 2nd-Level TLB: 4 KByte/2MByte pages, 8-way associative, 1024 entries"
#define MSGTLBC2 "DTLB: 4 KByte/2 MByte pages, 4-way associative, 16 entries"
#define MSGTLBC3 "Shared 2nd-Level TLB: 4 KByte /2 MByte pages, 6-way associative, 1536 entries. Also 1GBbyte pages, 4-way, 16 entries."
#define MSGTLBC4 ""
#define MSGTLBC5 ""
#define MSGTLBC6 ""
#define MSGTLBC7 ""
#define MSGTLBC8 ""
#define MSGTLBC9 ""
#define MSGTLBCA "Shared 2nd-Level TLB: 4 KByte pages, 4-way associative, 512 entries"
#define MSGTLBCB ""
#define MSGTLBCC ""
#define MSGTLBCD ""
#define MSGTLBCE ""
#define MSGTLBCF ""

#define MSGTLBD0 "3rd-level cache: 512 KByte, 4-way set associative, 64 byte line size"
#define MSGTLBD1 "3rd-level cache: 1 MByte, 4-way set associative, 64 byte line size"
#define MSGTLBD2 "3rd-level cache: 2 MByte, 4-way set associative, 64 byte line size"
#define MSGTLBD3 ""
#define MSGTLBD4 ""
#define MSGTLBD5 ""
#define MSGTLBD6 "3rd-level cache: 1 MByte, 8-way set associative, 64 byte line size"
#define MSGTLBD7 "3rd-level cache: 2 MByte, 8-way set associative, 64 byte line size"
#define MSGTLBD8 "3rd-level cache: 4 MByte, 8-way set associative, 64 byte line size"
#define MSGTLBD9 ""
#define MSGTLBDA ""
#define MSGTLBDB ""
#define MSGTLBDC "3rd-level cache: 1.5 MByte, 12-way set associative, 64 byte line size"
#define MSGTLBDD "3rd-level cache: 3 MByte, 12-way set associative, 64 byte line size"
#define MSGTLBDE "3rd-level cache: 6 MByte, 12-way set associative, 64 byte line size"
#define MSGTLBDF ""

#define MSGTLBE0 ""
#define MSGTLBE1 ""
#define MSGTLBE2 "3rd-level cache: 2 MByte, 16-way set associative, 64 byte line size"
#define MSGTLBE3 "3rd-level cache: 4 MByte, 16-way set associative, 64 byte line size"
#define MSGTLBE4 "3rd-level cache: 8 MByte, 16-way set associative, 64 byte line size"
#define MSGTLBE5 ""
#define MSGTLBE6 ""
#define MSGTLBE7 ""
#define MSGTLBE8 ""
#define MSGTLBE9 ""
#define MSGTLBEA "3rd-level cache: 12MByte, 24-way set associative, 64 byte line size"
#define MSGTLBEB "3rd-level cache: 18MByte, 24-way set associative, 64 byte line size"
#define MSGTLBEC "3rd-level cache: 24MByte, 24-way set associative, 64 byte line size"
#define MSGTLBED ""
#define MSGTLBEE ""
#define MSGTLBEF ""

#define MSGTLBF0 "64-Byte prefetching"
#define MSGTLBF1 "128-Byte prefetching"
#define MSGTLBF2 ""
#define MSGTLBF3 ""
#define MSGTLBF4 ""
#define MSGTLBF5 ""
#define MSGTLBF6 ""
#define MSGTLBF7 ""
#define MSGTLBF8 ""
#define MSGTLBF9 ""
#define MSGTLBFA ""
#define MSGTLBFB ""
#define MSGTLBFC ""
#define MSGTLBFD ""
#define MSGTLBFE ""
#define MSGTLBFF "CPUID leaf 2 does not report cache descriptor information, use CPUID leaf 4 to query cache parameters"

#endif//CACHE_H_HEADER_GUIRD
